//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string ANESTHETIC_DEPTH = "anesthetic_depth";
        
        public const string POWER_FAILURE = "power_failure";
        
        public const string ELECTROLYTE_LEVELS = "electrolyte_levels";
        
        public const string LIMITED_MOVEMENT = "limited_movement";
        
        public const string RESPIRATORY_RATE = "respiratory_rate";
        
        public const string CONNECTION_LOST = "connection_lost";
        
        public const string BLOOD_GLUCOSE_LEVELS = "blood_glucose_levels";
        
        public const string EXCESSIVE_FORCE = "excessive_force";
        
        public const string HEMAGLOBIN_HEMATOCRIT_LEVELS = "hemaglobin_hematocrit_levels";
        
        public const string SECURITY_THREAT = "security_threat";
        
        public const string SOFTWARE_MALFUNCTION = "software_malfunction";
        
        public const string BLOOD_PRESSURE = "blood_pressure";
        
        public const string BODY_TEMPERATURE = "body_temperature";
        
        public const string INSTRUMENT_MALFUNCTION = "instrument_malfunction";
        
        public const string HEART_RATE = "heart_rate";
    }
}
